---
language: custom.yml
---

**Просодия** --- раздел фонетики, изучающий, как при помощи просодических средств сегментные (минимальные) фонетические единицы организуются в более крупные и сложные просодические единицы. Система фонетических единиц имеет иерархическую структуру: из самых мелких, далее нечленимых сегментных единиц (звуков и фонем) образуются слоги, из слогов --- фонетические слова, из фонетических слов --- синтагмы, из синтагм --- фразы.

Основной способ просодической организации единиц --- выделение при помощи просодических средств (в первую очередь --- тона, длительности и интенсивности) одной из составляющих в качестве центра (звука в слоге, слога в фонетическом слове, фонетического слова в синтагме) и подчинение ей остальных, периферийных, составляющих.

Ядро слога выделяется за счет максимальной сонорности одного из сегментов (непосредственно связанной с его относительной интенсивностью), ядро фонетического слова --- за счёт ударения (противопоставления ударного слога безударным по длительности, качеству и интенсивности), ядро синтагмы --- при помощи фразового акцента (резкого изменения частоты основного тона, увеличения длительности и интенсивности).

Основные диалектные различия в области просодии связаны с

1) слогоделением;
2) ритмической структурой фонетического слова;
3) интонационным оформлением синтагмы;
4) темпом речи.

В современной автосегментно-метрической фонологии [@pierrehumbert80; @beckman86; @beckman05] просодия описывается как трехуровневая система, включающая в себя 

- **просодические единицы** разной размерности, 
- ассоциированные с ними **тональные явления** и 
- разделяющие их границы --- **просодические швы** (ПШ, ‘prosodic breaks’).

Просодические единицы образуют континуум от минимальных до самых крупных: мора (M) --- слог (Syl) --- стопа (F) --- лексическое слово в роли просодической единицы (Wd) --- фонетическое слово (prosodic word, PrWd) --- акцентная группа (accentual phrase, AP) --- синтагма (intermediate phrase, ip) --- фраза (intonational phrase, IP) --- высказывание (utterance, Ut). В языках мира набор этих единиц может быть различным.

Тональные просодические **явления** подразделяются на лексические (слоговые и словесные тоны) и постлексические (фразовые), собственно интонационные, ассоциированные с единицами, бóльшими чем слово: 

- **тональные акценты** (pitch accents, `N*`), служащие для выделения одной из единиц в ряду подобных[^1]; 
- начальные и конечные **пограничные тоны** (boundary tones, `%N`, `N%`), маркирующие границы между единицами;
- **фразовые тоны** (phrase accents, `N-`), связывающие тональные акценты и пограничные тоны[^2]. 

[^1]: Тональные акценты подразделяются на ядерные (nuclear), несущие основную коммуникативную нагрузку и тяготеющие к концу фразы, и неядерные (в том числе --- орнаментальные).
[^2]: Здесь перечислены основные функции, их набор этим, конечно, не исчерпывается.

Эти элементы просодической структуры в русских диалектах описаны в [@knyazev22o_strukture; @knyazev22o_frazovoy; @knyazev23severnorusskaya; @knyazev23frazoviy].

В системе просодической нотации ToBI N может принимать различные значения: стандартное описание предполагает использование двух тонов: высокого (`Н`) и низкого (`L`), в большинстве просодических описаний языков мира используются именно они [@jun05; @jun14]. В тех случаях, когда возникает необходимость введения промежуточного значения, может использоваться символ среднего тона (`М%`) или (чаще) применяться нотация с использованием знака `!H%` (даунстеп с высокого). Знак `^`, наоборот, маркирует акцент, реализующийся на более высоком уровне, чем предшествующий (upstep). Контурные тоны обозначаются с использованием символа `+`: восходящий --- `[L+H]`, нисходящий --- `[H+L]`. Базовыми вариантами восходящих акцентов являются `L*+H` и `L+H*`, где астериск маркирует тот тон, который наиболее стабильно ассоциируется с ударным слогом акцентоносителя.

##### Для цитирования:

Князев С. В., Мороз Г. А., Дьяченко С.В. Русская диалектная просодия. 2024. Электронный ресурс: https://agricolamz.github.io/russian_dialect_intonation_atlas/, (дата обращения ...)

## Ссылки на литературу
