---
title: "Корпус Просодии Русских Диалектов (ПРуД)"
language: custom.yml
---

Электронный ресурс «Корпус просодии русских диалектов» (ПРуД) содержит сведения о фразовой интонации и структуре фонетического слова в русских диалектах со звуковыми и визуальными иллюстрациями. 

Основная его задача состоит в ознакомлении всех желающих со *спецификой* просодической организации высказывания и его частей в говорах русского языка. В соответствии с этим представленный в базе данных материал отражает, в первую очередь, те просодические особенности, которые отличают диалектную просодию от литературной и обычно не является исчерпывающим для характеристики интонационной системы того или иного идиома. 

Основной массив данных отобран из диалектных записей С.В. Князева и С.В. Дьяченко и дополнен записями других диалектологов.

Просодическая аннотация материала выполнена в системе ToBI [@pierrehumbert80; @beckman94; @beckman97] с некоторой адаптацией ее к русскому материалу.

Для обработки звукового материала и подготовки интонограмм и сонаграмм использовалась программа PRAAT.

Участники проекта:

- С. В. Князев (ИРЯ РАН им. В.В. Виноградова) ---  общая концепция, создание текста, запись, отбор, расшифровка, транскрибирование, сегментация и просодическое аннотирование диалектных текстов, создание иллюстраций, обобщающих схем и таблиц.
- Г. А. Мороз (НИУ ВШЭ, Международная лаборатория языковой конвергенции) --- создание веб-сайта: разработка концепции, структуры и оформления сайта, программирование и наполнение баз данных.
- С. В. Дьяченко (ИРЯ РАН им. В.В. Виноградова) --- запись, расшифровка, транскрибирование, сегментация диалектных текстов, создание иллюстраций, обобщающих схем и таблиц. 

В работе использованы следующие источники:

- Личные звукозаписи С. В. Князева, С. К. Пожарицкой, С. В. Дьяченко, И. И. Исаева, О. Е. Кармаковой, И. А. Букринской, А. В. Тер-Аванесовой, А. В. Малышевой, Е. В. Колесниковой.
- Фонотека ИРЯ РАН,
- Фонотека кафедры русского языка филологического факультета МГУ,
- Диалектологический атлас русского языка. Часть 1. Фонетика. М., 1986,
- С. К. Пожарицкая. Русская диалектолгия. М., 2007.


##### Для цитирования:

Князев С. В., Мороз Г. А., Дьяченко С.В. Корпус Просодии Русских Диалектов. 2024. Электронный ресурс: https://LingConLab.github.io/PRuD/, (дата обращения ...)

