---
title: "Базовый инвентарь тональных средств СРЛЯ: эталонные примеры [@bryzgunova81]"
---

```{r}
create_image_look_up <- function(name,
                                 text = "&#x1f441;") {
  paste0(
    "<a ",
    "onmouseover=\"resize(this, '200%')\" ",
    "onmouseout=\"resize(this, '100%')\" ",
    "onclick = \"window.open('https://github.com/LingConLab/PRuD/raw/main/images/",
    name,
    ".png', 'targetWindow', 'toolbar=no, location=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1090px, height=550px, top=25px left=120px'); sound_play('https://github.com/LingConLab/PRuD/raw/main/audio/",
    name,
    ".wav');return false;\">",
    text,
    "</a>"
  )
}
```

### Тональные акценты (pitch accents)

- `(L+H)*` (восходящий): Восходящее движение тона на всем ударном слоге, тональный максимум может достигаться в инициали первого заударного слога. (ИК-3) `r create_image_look_up("бры1")`
- `H*+L` (нисходящий): Нисходящее движение тона на всем ударном гласном или большей его части. (ИК-2) `r create_image_look_up("бры7")`
- `(H+)L*` (нисходящий): Нисходящее движение тона на согласном инициали, завершающееся в начальной части ударного гласного. (ИК-1) `r create_image_look_up("бры7")`

### Конечные пограничные тоны (final boundary tones)

- `L%` (низкий): Низкий тон на конечном слоге во фразе. (ИК-1) `r create_image_look_up("бры1")`
- `H%` (высокий): Высокий тон на конечном слоге во фразе. (ИК-6) `r create_image_look_up("бры6")`
- `0` (трункация): Нулевая реализация пограничного тона при отсутствии заакцентных слогов (ИК-3 // ИК-6) `r create_image_look_up("бры00")`

### Фразовый тон (phrase accent)

- `H-`: Ровный высокий тон на всех заакцентных слогах кроме последнего (реже - последнего и предпоследнего) во фразе. (ИК-5) `r create_image_look_up("бры5")`
- `L-`: Ровный низкий тон на всех заакцентных слогах. В транскрипции обычно не отмечается. `r create_image_look_up("бры00")`

<script>
function sound_play(x) {
    var audio = new Audio();
    audio.src = x;
    audio.play();
  }
function resize(elem, percent) { 
  elem.style.fontSize = percent; 
  }
</script>

